### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by vitormalencar** [sindresorhus/sindresorhus#1]
👏👏👏👏 hahahaha

**Comment by JamesMGreene** [comment]
:trollface: 😭

**Comment by szmarczak** [comment]
Please close this. Don't ruin plz

**Comment by shreyasminocha** [comment]
`spinner.svg` gives it away anyway

**Comment by vitormalencar** [comment]
we can make it even better let me rename

**Comment by ozburo** [comment]
Can confirm, keeps spinning... hopefully this can be fixed in the next release.

**Comment by vitormalencar** [comment]
almost sure that the problem is related to this file 
https://github.com/sindresorhus/sindresorhus/blob/a8f62759fdc1e98539faf74a941f315439586f69/.gitattributes#L3

**Comment by szmarczak** [comment]
Guys I think I found a fix #2 we need to get this merged ASAP our lives depend on it...

**Comment by anrananran** [comment]
😂😹

**Comment by concaption** [comment]
😁

**Comment by ghost** [comment]
I feel trolled. Nice @sindresorhus 😆

**Comment by makbol** [comment]
I even tried to disable ublock thinking this is the issue :trollface:

**Comment by szmarczak** [comment]
@sindresorhus @makbol's idea is just pure evil! It's a must-have!

**Comment by nbili** [comment]
😭😭😭😭😭

**Comment by RobertoMachorro** [comment]
All your base are belong to us!

**Comment by RobertoMachorro** [comment]
![image](https://user-images.githubusercontent.com/7190436/87819767-cfe87d80-c83a-11ea-91a2-b537903a850d.png)

**Comment by Richienb** [comment]
Guys the pr opened by @szmarczak made the readme fail to display immediately. I fixed in #9

**Comment by szmarczak** [comment]
[removed spoiler]

**Comment by szmarczak** [comment]
Lovely approach doe!

**Comment by szmarczak** [comment]
Can we close the issue? @Richienb fixed this issue. Just wait a while and it loads :D
