### ISSUE TITLE
It's not loading 😂

### ISSUE THREAD

**Issue by jatin2003** [sindresorhus/sindresorhus#8]
Hey @sindresorhus 

It looks like there's something wrong with repo as It seems to be always loading. It's not an Internet Problem from my side 😜

**Comment by sindresorhus** [comment]
Try refreshing a couple of times. It loads eventually.

**Comment by palashmon** [comment]
Duplicate of #1

**Comment by jatin2003** [comment]
Oh! Issue [#1](https://github.com/sindresorhus/sindresorhus/issues/1) is the Same. So, I'm closing this Issue 💛
